[package]
name = "ember-lab-layer"
edition.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bytemuck.workspace = true
naga = { version = "24", features = ["wgsl-in"] }
serde.workspace = true
thiserror.workspace = true
wgpu = { workspace = true, features = ["wgsl"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["Document", "Element", "HtmlCanvasElement", "Performance", "Window"] }
wgpu = { workspace = true, features = ["webgl", "wgsl"] }

[lints]
workspace = true
