[package]
name = "ember-julibrot-shader"
edition.workspace = true
version = "1.3.0"

[features]
template-debug = ["minijinja/debug"]

[dependencies]
bytemuck.workspace = true
minijinja = { version = "=2.24.0", default-features = false, features = ["builtins", "deserialization", "macros", "multi_template", "adjacent_loop_items", "std_collections", "serde", "loop_controls"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
naga = { version = "=24.0.0", default-features = false, features = ["wgsl-in"] }

[dev-dependencies]
minijinja = { version = "=2.24.0", default-features = false, features = ["debug"] }

[lints]
workspace = true
