"""Three scoped existing-worker generation jobs; source assets stay outside checkout."""
from pathlib import Path
import argparse, ctypes, hashlib, json, os, subprocess, time, urllib.request

PROMPTS={
'soldier': 'One full body armored medieval castle soldier, standing symmetrical relaxed A pose, both empty arms held thirty degrees away from torso, open empty hands, legs separated, boots completely visible. Human anatomy, realistic detailed textured dark fantasy game sculpt. Face hidden in battered steel sallet helmet with dark narrow visor, modest iron pauldrons, segmented steel cuirass over faded oxblood red quilted tunic ending at hip, dark leather belt and buckles, visible armored thighs, knee guards, tall battered iron and leather boots. Strong readable sturdy silhouette, no cape, no skirt, no weapon. Entire figure centered on plain light grey background, orthographic front studio asset photography, neutral even lighting, sharp materials and anatomy.',
'hollow-knight': 'One full body terrifying hollow medieval axe knight, standing symmetrical A pose with both empty arms thirty degrees away from torso, open empty hands, legs separated, all boots visible. Realistic detailed textured dark fantasy game character sculpt. Gaunt skeletal face inside broken black iron helmet, empty dark eye sockets, jagged crown-like crest, broad ragged rusted iron shoulder plates, battered dark armor plates with deep scratches, torn charcoal cloth hip-length surcoat with split tattered hem, rope belt, visible separate armored legs and knee guards, heavy boots. Desiccated pale grey exposed skin, sinister warrior silhouette, aged rust and dust, no cape, no weapon. Entire figure centered on plain light grey background, orthographic front studio asset photography, neutral even lighting.',
'cyclops': 'One full body huge terrifying cyclops castle lord monster, symmetrical A pose with both empty arms thirty degrees away from torso, open empty hands, two widely separated legs, all feet visible. Exactly ONE enormous eye centered in the forehead above the nose, absolutely no two ordinary human eyes, thick continuous bony brow, bald scarred head, fierce tusked mouth. Bulky muscular humanoid ogre with broad shoulders, thick powerful arms and legs, mottled pale weathered grey flesh. Blackened iron shoulder armor, iron rings and leather harness across massive chest, broad belt, short ragged brown loincloth ending at upper thigh, knee straps, thick battered leather boots. Realistic highly detailed textured dark fantasy game sculpt, strong heavy silhouette. No weapon, no background objects. Entire figure centered on plain light grey background, orthographic front studio asset photography, neutral even lighting.'}
NEGATIVE='cropped, closeup, portrait, two people, multiple characters, duplicate limbs, fused arms, fused legs, hands touching body, crossed arms, hands on hips, sword, spear, axe, club, maul, shield, weapon, scenery, text, watermark, logo, cute, cartoon, toy, smooth plastic, long robe, floor length coat, cape, wings, blurry'
CLI=Path(os.environ.get('ASSET_FORGE_CLI','C:/Users/end/dev/cluster/provision/asset-forge/asset_cli.py'))
PROMPTS['hollow-knight']='One full body terrifying unarmed hollow medieval warrior, symmetric T pose, both arms straight out horizontally away from body, both hands open showing palms, ten fingers visible, empty hands, legs separated and all boots visible. Realistic detailed textured dark fantasy game character sculpt. Gaunt skeletal face inside broken black iron helmet, empty dark eye sockets, jagged crown-like crest, broad ragged rusted iron shoulder plates, battered dark armor with deep scratches, torn charcoal cloth hip-length tunic, rope belt, visible separate armored legs and knee guards, heavy boots. Desiccated pale grey exposed skin, sinister warrior silhouette, aged rust and dust. Entire figure centered on plain light grey background, orthographic front studio asset photography, neutral even lighting.'
ROOT=Path(os.environ.get('END_GAME_V10_WORK',str(Path(__file__).resolve().parent)))
def main():
 p=argparse.ArgumentParser();p.add_argument('character',choices=PROMPTS);p.add_argument('stage',choices=['image','cutout','mesh']);p.add_argument('--input',type=Path);a=p.parse_args()
 if os.name=='nt':ctypes.windll.kernel32.SetPriorityClass(ctypes.windll.kernel32.GetCurrentProcess(),0x40)
 work=ROOT/a.character;dest=work/a.stage;dest.mkdir(parents=True,exist_ok=True);seed=1009182 if a.character=='hollow-knight' else 1009081+list(PROMPTS).index(a.character)
 if a.stage=='image':
  queue=json.load(urllib.request.urlopen('http://192.168.178.187:8188/queue'));assert not queue['queue_running'] and not queue['queue_pending'],'SDXL busy'
  tool='image_generate';args=dict(prompt=PROMPTS[a.character],negative=NEGATIVE,width=1024,height=1536,steps=35,cfg=6.5,seed=seed,local_dir=str(dest),timeout_s=600)
 elif a.stage=='cutout':tool='image_cutout';args=dict(image=str(a.input),local_dir=str(dest),margin=.06)
 else:
  health=json.load(urllib.request.urlopen('http://192.168.178.171:8190/health'));assert health['model_loaded'] and health['current_job'] is None and health['queued']==0,'TRELLIS busy'
  tool='mesh_generate_pbr';args=dict(image=str(a.input),seed=seed,texture_size=2048,local_dir=str(dest),timeout_s=1200)
 argsfile=work/(a.stage+'-arguments.json');argsfile.write_text(json.dumps(args,indent=2)+'\n',encoding='utf-8',newline='\n')
 started=time.perf_counter();r=subprocess.run([os.sys.executable,str(CLI),tool,'@'+str(argsfile)],capture_output=True,text=True,encoding='utf-8',errors='replace')
 record=dict(tool=tool,arguments=args,stdout=r.stdout,stderr=r.stderr,exit_code=r.returncode,wall_seconds=round(time.perf_counter()-started,3),utc=time.strftime('%Y-%m-%dT%H:%M:%SZ',time.gmtime()),input_sha256=hashlib.sha256(a.input.read_bytes()).hexdigest() if a.input else None)
 (work/(a.stage+'-result.json')).write_text(json.dumps(record,indent=2)+'\n',encoding='utf-8',newline='\n');print(json.dumps(record),flush=True);raise SystemExit(r.returncode)
if __name__=='__main__':main()
