[package]
name = "league-core"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
ember-net = { path = "../ember-net" }
serde = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
proptest = "1"

[lib]
crate-type = ["rlib"]
