[package]
name = "ember-julibrot-kernels"
edition.workspace = true
version.workspace = true

[features]
default = []
math-oracles = []

[dependencies]
bytemuck.workspace = true
ember-julibrot-math = { path = "../math" }
ember-lab-heap = { path = "../../heap" }
thiserror.workspace = true

[lints]
workspace = true
