[package]
name = "ember-julibrot-kernels"
edition.workspace = true
version.workspace = true

[dependencies]
bytemuck.workspace = true
ember-julibrot-math = { path = "../math" }
ember-lab-heap = { path = "../../heap" }
thiserror.workspace = true
wgpu = { workspace = true, features = ["webgl", "wgsl"] }

[dev-dependencies]
naga = { version = "=24.0.0", default-features = false, features = ["wgsl-in", "glsl-out"] }

[lints]
workspace = true
